name: SonarQube Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          sonar-projectKey: OmniaPotentia_moxakk-server_ab1d8c26-93b9-42dd-a1a9-5f12a59bc3e6
          sonar-host-url: http://188.245.58.93:9000
          sonar-token: ${{ secrets.SONAR_TOKEN }}
